# Generated by Django 2.0.5 on 2018-05-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.TextField(max_length=64)),
                ('zip_code', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('company_email', models.EmailField(max_length=256)),
                ('company_website', models.CharField(max_length=256)),
                ('company_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_code', models.CharField(default='1', max_length=2)),
                ('area_code', models.CharField(max_length=3)),
                ('prefix', models.CharField(max_length=3)),
                ('suffix', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=256)),
                ('ref_email', models.EmailField(max_length=256)),
                ('ref_website', models.CharField(max_length=256)),
                ('ref_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Address')),
                ('ref_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Company')),
                ('ref_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Phone')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('degree', models.CharField(choices=[('AD', 'Associates Degree'), ('BD', 'Bachelors Degree'), ('MD', 'Masters Degree'), ('DD', 'Doctoral Degree')], default='BD', max_length=2)),
                ('major', models.CharField(default='Business Administration', max_length=256)),
                ('focus', models.CharField(default='General Business', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=256)),
                ('years', models.IntegerField()),
                ('years_modifier', models.CharField(max_length=2)),
                ('job', models.ManyToManyField(to='resume.Job')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Phone'),
        ),
    ]
