# Generated by Django 2.0.5 on 2018-05-18 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('updated_at', resume.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'zip_code')},
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('title', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('area_code', 'prefix', 'suffix')},
        ),
        migrations.AddField(
            model_name='reference',
            name='relation',
            field=models.ForeignKey(default='Manager', on_delete=django.db.models.deletion.CASCADE, to='resume.Relation'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'degree', 'major')},
        ),
    ]
