# Generated by Django 2.0.5 on 2018-05-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180518_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Relation'),
        ),
    ]
