# Generated by Django 2.0.5 on 2018-05-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180518_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='relation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Relation'),
        ),
    ]
