# Generated by Django 2.0.5 on 2018-05-16 15:25

import datetime
from django.db import migrations
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180516_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=resume.models.AutoDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=resume.models.AutoDateTimeField(default=datetime.datetime.now),
        ),
    ]
