# Generated by Django 2.0.5 on 2018-05-16 15:30

from django.db import migrations
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180516_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=resume.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=resume.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
