# Generated by Django 2.0.5 on 2018-05-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20180516_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(blank=True, to='resume.Skill'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Address'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_phone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Phone'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_website',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years_modifier',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
