# Generated by Django 2.0.5 on 2018-05-20 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('updated_at', resume.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='resume2comp', to='resume.Company'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='resume2job', to='resume.Job'),
        ),
        migrations.AddField(
            model_name='resume',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='resume2ref', to='resume.Reference'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='resume2skill', to='resume.Skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.ResumeType'),
        ),
    ]
