# Generated by Django 2.0.5 on 2018-05-21 06:17

from django.db import migrations, models
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20180521_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(unique=True)),
                ('updated_at', resume.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='duty',
            field=models.ManyToManyField(blank=True, related_name='job2duty', to='resume.Duty'),
        ),
    ]
