# Generated by Django 2.0.5 on 2018-05-23 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20180521_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('website', models.CharField(blank=True, max_length=256)),
                ('linked_in', models.CharField(blank=True, max_length=256)),
                ('updated_at', resume.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Address')),
                ('phone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='resumeowner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.ResumeOwner'),
            preserve_default=False,
        ),
    ]
