# Generated by Django 2.0.5 on 2018-05-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20180524_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resumeowner',
            new_name='resume_owner',
        ),
    ]
