# Generated by Django 2.0.6 on 2018-06-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('title', 'company', 'start')},
        ),
    ]
