# Generated by Django 2.0.5 on 2018-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20180523_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeowner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resumeowner',
            name='facebook',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='resumeowner',
            name='last_name',
            field=models.CharField(default='Greg', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeowner',
            name='name_web_display',
            field=models.CharField(default='Greg Slavens', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeowner',
            name='social_media_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='resumeowner',
            name='social_media_2',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
