# Generated by Django 2.0.5 on 2018-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20180524_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeowner',
            name='github',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
