# Generated by Django 2.0.5 on 2018-05-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20180518_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(blank=True, related_name='skill', to='resume.Skill'),
        ),
    ]
