# Generated by Django 2.0.5 on 2018-05-21 04:28

from django.db import migrations, models
import django.utils.timezone
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20180520_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('desc', models.TextField(blank=True)),
                ('updated_at', resume.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.ManyToManyField(blank=True, related_name='resume2summary', to='resume.Summary'),
        ),
    ]
